#!/bin/bash

vim +PluginUpdate +qall

ACKGREP=`which ack-grep`
if [ -z ${ACKGREP} ]; then
    sudo apt-get install ack-grep
fi

pushd ~/.vim/bundle/YouCompleteMe
./install.sh --omnisharp-completer --clang-completer
popd

pushd ~/.vim/bundle/vimproc.vim
make
popd

NPM=`which npm`
if [ -f $NPM ]; then
	$NPM install -g typescript-tools
fi
